name: mationani
description: create animation by stateless widget
version: 0.0.44
repository: https://github.com/nomagicisreal/mationani

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true